services:
  postgres:
    image: postgres:16-alpine
    container_name: techmaster-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techmaster
    ports:
      - "5432:5432"
    volumes:
      - techmaster_pgdata:/var/lib/postgresql/data

volumes:
  techmaster_pgdata:
